### ISSUE TITLE
Describe the global css variable to color for changing dark/light theme

### ISSUE THREAD

**Issue by Sahillather002** [Sahillather002/ProductsStore#1]

**Comment by Samaresh-Das** [comment]
Would like to work on this issue

**Comment by Sahillather002** [comment]
sure go ahead i am also working currently for the frontend part of my website.
I added lib for basic light / dark theme switch.
But i hard coded the color do them global.

**Comment by Samaresh-Das** [comment]
Thanks, I will be working in it. Can you please formally assign this me here.

**Comment by Sahillather002** [comment]
Please check and start working on it.

**Comment by Samaresh-Das** [comment]
I did the fixes but do you want it in a new branch or default is OK?

**Comment by Sahillather002** [comment]
bro go with branch

**Comment by Samaresh-Das** [comment]
#5  Did the PR, you can checkout.

**Note -** 
While I get it the project is in its early stages, here are some of my recommendations
- There are some hydration problems even before I started working, that need to be fixed.
- Code splitting is needed.
